### ISSUE TITLE
Import Swagger schema

### ISSUE THREAD

**Issue by ad-m** [GraphQL-Designer/graphqldesigner.com#172]
What do you think about import Swagger schema for model definition importing?

**Comment by Tsionad** [comment]
Hi Adam! Thanks for suggesting implementing swagger!

We're not quite as familiar with swagger yet, but curious to try it out- how well are you familiar with it?

**Comment by ad-m** [comment]
Swagger (OpenAPI) is standard to define the REST API specifications. GraphQL displaces the REST API in many companies. Companies have REST API documentation and may want to see how their API looks as GraphQL, or start migrating to GraphQL.

Swagger contain definition of data model exposed to user. See example at https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml#L82-L109 . So for your tool intteresting is only import of "Schema Object" which specs is available at https://swagger.io/specification/#schemaObject (for Swagger 3.0 ak. OpenAPI) and https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object (for Swagger 2.0 which are still quite popular).

Could you import (even partially for manual fix) "Schema object"?
