### ISSUE TITLE
The Legend is wrong for Required and Unique

### ISSUE THREAD

**Issue by dbrockman** [GraphQL-Designer/graphqldesigner.com#173]
The Legend says
```
Required : *
Unique : !
```
but it should say
```
Required : !
Unique : *
```

**Comment by dbrockman** [comment]
Here: https://github.com/GraphQL-Designer/graphqldesigner.com/blob/1cf59aff27bf0b99a7a9678d98d7fcc68f642a00/client/components/schema/sidebar/create-table.js#L178-L179
Sorry, can't be bothered to create a PR :)

**Comment by Tsionad** [comment]
Thank you for bringing this up--we've fixed the typo!
