### ISSUE TITLE
Persistence of specifications

### ISSUE THREAD

**Issue by ad-m** [GraphQL-Designer/graphqldesigner.com#179]
I think it would be convenient if you could return to the model you started. The first version is enough if the specification can be saved to "localStorage" and then read from "localStorage". You can also export to a JSON file and import to a JSON file to show your friends what a great tool it is.

In the target version, the GraphQL specification created could be stored on the platform side or on the Gist GitHub side and read from there when the user returns.

This will allow you to create a few sample specifications and link them, which will allow the user to instantly feel the greatness of the tool effortlessly on his part.

**Comment by manishagarwal23** [comment]
is this still being worked upon ?
